### ISSUE TITLE
Make bob example lispier

### ISSUE THREAD

**Issue by yurrriq** [exercism/xlfe#4]
Likely using `cond` and/or `if` forms.

**Comment by oubiwann** [comment]
You mean instead of ``case``? I'd leave it as-is. One of the really cool things about the LFE dialect of Lisp is its Erlang inheritance; ``case`` can be used quite elegantly in LFE (it's also one of the most prevalent conditionals in Erlang, so its appearance would be familiar to those coming to LFE from Erlang).

**Comment by yurrriq** [comment]
👍
