### ISSUE TITLE
leap-year updates

### ISSUE THREAD

**Issue by yurrriq** [exercism/xlfe#7]
- [x] Rename `leap-year` to `leap-year?`
- [ ] Investigate pre-Gregorian dates and add test(s)

**Comment by yurrriq** [comment]
[Pre-Gregorian context](http://exercism.io/submissions/9512f4def6c042b2aeca3a5cd45de235)

**Comment by verdammelt** [comment]
To throw more wrenches into this fire: 

https://en.wikipedia.org/wiki/Proleptic_Gregorian_calendar

**Comment by hdurer** [comment]
I wouldn't delve too much into pre-Gregorian calendars or even into the time near the switch-over.
Anything time related is one huge trap.  There are better ways to spend your time...

I only added that precondition as the minimal sensible check on the inputs.  Really, the function should return `false` for other inputs since leap years didn't exist before that, IIRC.

Of course this whole task is also all culturally insensitive as it assumes our western, Christian calendar.

**Comment by yurrriq** [comment]
No need to shave every yak.
